spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  application:
    name: user-service
server:
  port: 8083
  error:
    include-message: always